# Site settings
title: ZenWave Code Generator
description: DDD and API-First Modeling Tools
github_username: ivangsa
# Theme settings
remote_theme: amitmerchant1990/reverie
#remote_theme: just-the-docs/just-the-docs
#search_enabled: true
#logo: 'https://avatars.githubusercontent.com/u/93670347'git